Fix issue where new memory model would crash
icerockdev/moko-permissions pull request #72
Opened 2023-02-26 09:05 UTC by codlab

Compatible with 1.7.20 onward (tested with 1.8.0)

fixing the IllegalArgumentException: Failed requirepement.

2023-02-28 15:38 UTC, codlab commented
Interesting that the actions are failing. Lemme check locally if I have some differences

2023-02-28 23:33 UTC, codlab commented
The NPE was due to application of the compose plugin. Made it so that it would use 1.3.0. I also made a modification so that the linter part would pass.

And I also didn't notice that the branch was actually from master, retrenched my 2 commits to develop (compilation passes on both master & develop)

2023-04-08 13:52 UTC, Alex009 requested changes

2023-04-08 13:52 UTC, Alex009 commented on build.gradle.kts
> +}
duplication - compose plugin already added. to update version you should just change version in libs:
```
composeJetBrainsVersion = "1.1.1"
```

2023-04-09 13:53 UTC, Alex009 approved these changes

2023-04-09 14:25 UTC, merged