Add Contacts For Android/IOS
icerockdev/moko-permissions pull request #88
Opened 2023-08-15 07:45 UTC by hellomr3

Add Contacts For Android/IOS

2023-09-28 19:57 UTC, burnoo commented
Hey! Are there any blockers to release it?

2023-11-15 09:20 UTC, hellomr3 commented
fix it

2023-12-07 12:05 UTC, Alex009 requested changes
code reformat required to fix detekt issues

2023-12-07 13:21 UTC, Alex009 approved these changes

2023-12-07 13:22 UTC, merged